import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { SiteHeader } from "@/components/site-header";
import { LocalizedTimestamp } from "@/components/localized-time";
import { requireAdmin } from "@/lib/auth";
import { getCertificateUploadContext } from "@/services/certificate-service";
import styles from "@app/admin/admin.module.css";

export const dynamic = "force-dynamic";
export const metadata: Metadata = { title: "Certificate status" };

export default async function CertificateIssuePage({ params }: { params: Promise<{ id: string }>; searchParams?: Promise<unknown> }) {
  const admin = await requireAdmin();
  const { id } = await params;
  if (!/^[A-Za-z0-9_-]{1,64}$/.test(id)) notFound();
  const registration = await getCertificateUploadContext(id);
  if (!registration) notFound();
  return <>
    <SiteHeader user={admin} current="admin" />
    <main id="main-content" tabIndex={-1} className={styles.shell}>
      <Link className={styles.backLink} href={`/admin/events/${registration.eventId}`}>← Back to participants</Link>
      <section className={styles.formPanel} aria-labelledby="certificate-title">
        <p className={`eyebrow ${styles.eyebrow}`}>Verified participation</p>
        <h1 id="certificate-title">Certificate status</h1>
        <p>{registration.participant.name} · {registration.event.title}</p>
        {registration.certificate ? <p><Link className={styles.button} href={`/certificates/${registration.certificate.token}`}>View certificate</Link></p> : <p className={styles.notice} role="status">
          {registration.checkedInAt ? "Arrival is recorded. Scan the participant’s QR again after the event ends to verify onsite presence and issue their HTML certificate." : "Record an arrival scan at any time, followed by a second onsite scan after the event ends."}
          {" "}Final scans open <LocalizedTimestamp value={registration.event.endsAt.toISOString()} /> and close <LocalizedTimestamp value={new Date(registration.event.endsAt.getTime() + 3_600_000).toISOString()} />.
        </p>}
        {registration.certificateKey && registration.certificateUploadedAt ? <p><Link href={`/api/certificates/${registration.id}`}>Download existing PDF</Link></p> : null}
        <p>New certificates are generated by the app. PDF uploads and replacements have been retired.</p>
      </section>
    </main>
  </>;
}
